### ISSUE TITLE
ploidetect for Pacbio

### ISSUE THREAD

**Issue by ywzhang071394** [lculibrk/Ploidetect#16]
Is Ploidetect compatible to Pacbio HiFi WGS sequencing?
I saw the sequencing type setting does not include Pacbio.

> # sequence type - "short" for BGI/illumina and "ont" for nanopore
> sequence_type: "short"

Thanks!

**Comment by lculibrk** [comment]
In principle it should be compatible using the "ont" preset

**Comment by ywzhang071394** [comment]
Hi,

I am trying to use singularity mode of ploidetect-package but get the error:

failed to get checksum for docker://lculibrk/Ploidetect:latest: unable to parse image name docker://lculibrk/Ploidetect:latest: invalid reference format: repository name must be lowercase


I am not sure whether you have new docker image. This image seems not work.

Thanks,
Yuwei

**Comment by lculibrk** [comment]
hi @ywzhang071394 ,

the docker container is `docker://lculibrk/ploidetect:latest`
